# Reference docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build.environment]
  VUE_APP_MATOMO_SITE_ID = 245


[[redirects]]
  from = "/*"
  to = "/index.html"
  force = false
  status = 200
