# Reference docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[[redirects]]
  from = "/*"
  to = "/index.html"
  force = false
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
