name: Build and deploy (production)

on:
  workflow_call:
  # workflow_run:
  #   workflows: ['Build and deploy (v2)']
  #   types: ['completed']

jobs:
  # if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_type == 'tag' }}

  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Assign env variables to a .env file
      run: env | grep VUE_APP > .env.production.local
      env:
        VUE_APP_MATOMO_SITE_ID: 244
        VUE_APP_API_ENDPOINT: "https://cartobio.agencebio.org/api"
        VUE_APP_CURRENT_CAMPAGNE_PAC: 2022

    - run: npm clean-install-test
    - run: npm run build

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ secrets.AGENCEBIO_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.AGENCEBIO_SSH_KNOWN_HOSTS }}

    - name: rsync
      run: |
        rsync -avzr --delete --exclude 'node_modules' --exclude '.git*' ./dist/ ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}
      env:
        REMOTE_HOST: ${{ secrets.AGENCEBIO_SSH_HOST }}
        REMOTE_USER: ${{ secrets.AGENCEBIO_SSH_USERNAME }}
        REMOTE_PATH: /var/www/cartobio.agencebio.org/
