name: Docker Image CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    branches:
      - master
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Assign env variables to a .env file
      run: env | grep VUE_APP > .env.production.local
      env:
        VUE_APP_API_IGN: ${{ secrets.VUE_APP_API_IGN }}
        VUE_APP_GEOSERVER_PREFIX: "https://cartobio.org/geoserver/gwc/service/tms/1.0.0/cartobio:anon_rpgbio_"
        VUE_APP_GEOSERVER_SUFFIX: "@EPSG:900913@pbf/{z}/{x}/{y}.pbf"
        VUE_APP_ESPACE_COLLAB_LOGIN: ${{ secrets.VUE_APP_ESPACE_COLLAB_LOGIN }}
        VUE_APP_ESPACE_COLLAB_PASSWORD: ${{ secrets.VUE_APP_ESPACE_COLLAB_PASSWORD }}
        VUE_APP_NOTIFICATIONS_ENDPOINT: "https://cartobio.org/api/notifications"
        VUE_APP_COLLABORATIF_ENDPOINT: "https://cartobio.org/api/espacecollaboratif"

    - uses: jerray/publish-docker-action@v1.0.3
      with:
        repository: agencebio/cartobio-presentation
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        auto_tag: true
