name: Docker Image CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    branches:
      - master
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: jerray/publish-docker-action@v1
      env:
        VUE_APP_API_IGN: ${{ secrets.VUE_APP_API_IGN }}
        VUE_APP_GEOSERVER_PREFIX: ${{ secrets.VUE_APP_GEOSERVER_PREFIX }}
        VUE_APP_GEOSERVER_SUFFIX: ${{ secrets.VUE_APP_GEOSERVER_SUFFIX }}
        VUE_APP_ESPACE_COLLAB_LOGIN: ${{ secrets.VUE_APP_ESPACE_COLLAB_LOGIN }}
        VUE_APP_ESPACE_COLLAB_PASSWORD: ${{ secrets.VUE_APP_ESPACE_COLLAB_PASSWORD }}
        VUE_APP_NOTIFICATIONS_ENDPOINT: http://cartobio.org:8000/notifications
        VUE_APP_COLLABORATIF_ENDPOINT: http://cartobio.org:8000/espacecollaboratif
      with:
        repository: agencebio/cartobio-presentation
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        auto_tag: true
