name: Build and deploy (v2)

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'bin/**'
    - 'infrastructure/**'
    - '*.example'
    - 'netlify.toml'
    - '*.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'

    - name: Assign env variables to a .env file
      run: env | grep VUE_APP > .env.production.local
      env:
        VUE_APP_SITE_ID: 244
        VUE_APP_API_ENDPOINT: "https://cartobio.org/api"

    - run: npm clean-install-test
    - run: npm run build

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.1
      if: github.ref == 'refs/heads/v2'
      with:
        key: ${{ secrets.AGENCEBIO_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.AGENCEBIO_SSH_KNOWN_HOSTS }}

    - name: rsync
      if: github.ref == 'refs/heads/v2'
      run: |
        rsync -avzr --delete --exclude 'node_modules' --exclude '.git*' ./dist/ ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}
      env:
        REMOTE_HOST: ${{ secrets.AGENCEBIO_SSH_HOST }}
        REMOTE_USER: ${{ secrets.AGENCEBIO_SSH_USERNAME }}
        REMOTE_PATH: /var/www/cartobio.agencebio.org/
