name: Docker Image CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'bin/**'
    - 'infrastructure/**'
    - 'src/workers/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'

    - name: Assign env variables to a .env file
      run: env | grep VUE_APP > .env.production.local
      env:
        VUE_APP_API_IGN: ${{ secrets.VUE_APP_API_IGN }}
        VUE_APP_GEOSERVER_PREFIX: "https://cartobio.org/geoserver/gwc/service/tms/1.0.0/cartobio:anon_rpgbio_"
        VUE_APP_GEOSERVER_SUFFIX: "@EPSG:900913@pbf/{z}/{x}/{y}.pbf"
        VUE_APP_API_ENDPOINT: "https://cartobio.org/api"
        VUE_APP_NOTIFICATIONS_ENDPOINT: "https://cartobio.org/api/notifications"
        VUE_APP_COLLABORATIF_ENDPOINT: "https://cartobio.org/api/espacecollaboratif"

    - run: npm clean-install-test
    - run: npm run build

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.1
      if: github.ref == 'refs/heads/main'
      with:
        key: ${{ secrets.AGENCEBIO_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.AGENCEBIO_SSH_KNOWN_HOSTS }}

    - name: rsync
      if: github.ref == 'refs/heads/main'
      run: |
        rsync -avzr --delete --exclude 'node_modules' --exclude '.git*' ./dist/ ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}
      env:
        REMOTE_HOST: ${{ secrets.AGENCEBIO_SSH_HOST }}
        REMOTE_USER: ${{ secrets.AGENCEBIO_SSH_USERNAME }}
        REMOTE_PATH: /var/www/cartobio.org/
