name: Netlify Preview
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci --no-audit
      - run: npm run build
        env:
          VUE_APP_API_IGN: ${{ secrets.VUE_APP_API_IGN }}
          VUE_APP_GEOSERVER_PREFIX: "http://91.134.137.224:8088/geoserver/gwc/service/tms/1.0.0/cartobio:anon_rpgbio_"
          VUE_APP_GEOSERVER_SUFFIX: "@EPSG:900913@pbf/{z}/{x}/{y}.pbf"
          VUE_APP_ESPACE_COLLAB_LOGIN: ${{ secrets.VUE_APP_ESPACE_COLLAB_LOGIN }}
          VUE_APP_ESPACE_COLLAB_PASSWORD: ${{ secrets.VUE_APP_ESPACE_COLLAB_PASSWORD }}
          VUE_APP_NOTIFICATIONS_ENDPOINT: "http://cartobio.org:8000/notifications"
          VUE_APP_COLLABORATIF_ENDPOINT: "http://cartobio.org:8000/espacecollaboratif"

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0.1
        with:
          publish-dir: './dist'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
